name: 'Checkout current repository'
description: 'Checkout current repository to source folder.'
runs:
  using: "composite"
  steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: source
